### ISSUE TITLE
Integrate Concurix into supervisor/pm

### ISSUE THREAD

**Issue by chandadharap** [strongloop/strong-supervisor#95]
Review Tetsuo's code/PR, merge etc. On staging for Sean to work with.

**Comment by sam-github** [comment]
Effort involved depends on the goal:

- On staging for internal use only

We can't merge to master, I "think", until its publishable (merging to master if we can't publish blocks all subsequent bug fixes and features from being published, ouch). But, we can merge to a "next major" branch, so it will be on staging, and Sean can use it.

In this case, all effort is on @Setogit, not me, I'll just review his PRs.

- publishable

I think we are required to remove the concurix name from the repos (because we didn't get trademark rights). This will involve a tedious walk through the code base to rename all the github repos, and to rename the packages in the repo.

I assume we aren't doing this now.

**Comment by chandadharap** [comment]
On staging for internal use until Arc is ready to publish the feature.

**Comment by sam-github** [comment]
At a high level, the things missing are:

- [ ] using node IPC to communicate from concurix, to supervisor, to pm
- [ ] tests

**Comment by sam-github** [comment]
POC is complete, closing this issue, replacing it with https://github.com/strongloop-internal/scrum-nodeops/issues/344
